import { Geist, Geist_Mono } from "next/font/google";
import "@uploadthing/react/styles.css";
import "./globals.css";
import NavbarBottom from "@/components/NavbarBottom";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className="main">{children}</main>
        <NavbarBottom></NavbarBottom>
        <Toaster
          position="top-center"
          toastOptions={{
            className: "",
            style: {
              background: " rgba(255, 255, 255, 0.34)",
              boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
              backdropFilter: "blur(7.1px)",
              padding: "12px",
            },
          }}
        />
      </body>
    </html>
  );
}
