import "@uploadthing/react/styles.css";
import "./globals.css";
import NavbarBottom from "@/components/NavbarBottom";
import { ImageCountProvider } from "@/context/ImageCountContext";
import { Toaster } from "react-hot-toast";
import { Lora, Inter, Parisienne } from "next/font/google";
import { connection } from "next/server";
import { Suspense } from "react";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

const parisienne = Parisienne({
  weight: "400", // Specify weight if available, often '400' for scripts
  subsets: ["latin"],
  variable: "--font-parisienne",
  display: "swap", // Optimizes font loading
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//OVO JE IZ UPLOADTHING DOKUMENTACIJE
async function UTSSR() {
  await connection();
  return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${parisienne.variable} ${lora.variable} ${inter.variable}`}
      >
        <Suspense>
          <UTSSR />
        </Suspense>
        <ImageCountProvider>
          <main className="main">{children}</main>
          <NavbarBottom></NavbarBottom>
          <Toaster
            position="top-center"
            toastOptions={{
              className: "",
              style: {
                background: " rgba(255, 255, 255, 0.34)",
                boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
                backdropFilter: "blur(8.1px)",
                padding: "14px",
                marginTop:'2rem'
              },
            }}
          />
        </ImageCountProvider>
      </body>
    </html>
  );
}
